<?php
// Auther: Walid Bakr
// Date: 2024-07-15
// Last Update: 2025-06-17
// Description: Langauge ENGLISH STATEMENTS

//English version
function fn_lang($phrase)
{
    static $lang = array(
        //Navbar Links
        'HOME_ADMIN' => 'Home',
        'USERPROFILE' => "Profile",
        'PROFILE' => "My Profile",
        'QUESTIONS' => 'My questions',
        'LANG' => 'Langauges',
        'EXIT' => "Logout",
        'ENGLISH' => "English",
        'ARABIC' => "Arabic",
        'WELCOME' => "Welcome",
        'CREATEDQ' => "Created questions",
        'APPROVEDQ' => "Approved questions",
        'USERCREAT' => "You creates",
        'QG' => "Question Generator",
        'URGENT' => "Urgent",
        'CREATEQ' => "Create new Question",
        'GETQ' => "Collect Questions",
        'EDITQ' => "Edit Question",
        'DELETEQ' => "Delete Question",
        'DATAQ' => "Questions Database",
        'ACCOUNT' => "My Account",
        'CREATED' => "CREATED",
        'SUBMITTED' => "SUBMIT",
        'RESULT' => "Results",
        'QCREATOR' => "Question Generator Area",
        'URGQ' => "Urgent Questions",
        'VIDEO' => "Videos",
        //New Question SECTION
        'TYPE' => "Type of Education",
        'STAGE' => "Stage",
        'SUBJECT' => "Subject",
        'GRADE' => "Grade",
        'OUTCOME' => "Learning Outcome",
        'QCONSTRUCT' => "Question Construction",
        'WRITTER' => "Question Writter",
        'DATE' => "Creation Date",
        'EDITDATE' => "Edit Date",
        'REVDATE' => "Revision Date",
        'RESDATE' => "Resume Date",
        'DEPTH' => "Depth of knowledge",
        'DOK' => "Guide for choosing the DOK",
        'RECALL' => "Recall",
        'DIRECT' => "Basic Application",
        'STRATEGIC THINKNG' => "Strategic Thinking",
        'NO_REF' => "No Reference",
        'BRAND_NEW' => "Brand New",
        'REF_SELECT' => "Adjusted From Reference",
        'REFERENCE' => "Reference Name",
        'REF' => "Type Name of the Reference and Page",
        'IMAGE' => "Insert Image, Drawing or Figure",
        'STEM' => "Stem of Question",
        'STEMQ' => "Stem of Question",
        'SUBSTEM' => "Sub Stem (Optional)",
        'OPTION' => "Insert Image instead of written",
        'QUESTION' => "Option and distractors",
        'CHOICE' => "Choice Number",
        'TRUE' => "Check if it is true answer",
        'CAUSE' => "Cause of choosing this answer",
        'SAVE' => "Save Question...",
        'SEND' => "Send to Revision",
        'TABLESHOW' => "Show Records",
        'EDIT' => "EDIT",
        'DELETE' => "DELETE",
        'REVISOR' => "Revision Page",
        //profile page
        'SAVEPROFILE' => "Save Profile...",
        'OLDPASSWORD' => "Old Password",
        'PASSWORD' => "Password",
        'CONFIRM' => "Confirm Password",
        'PASSCHANGE' => "Change Old Password",
        'DELETEPROFILE' => "Delete Profile",
        //Video Page
        'VIDEOPAGE' => "Introductory Videos",
        'VIDEOLINK' => "Video Links",
        'VID1' => "Foundation idea PART 1",
        'VID2' => "Foundation idea PART 2",
        'VID3' => "Learning Outcome PART 1",
        'VID4' => "Learning Outcome PART 2",
        'VID5' => "Workshop - Creating a Question Practically",
        'VID6' => "Welcome Meeting PART 1",
        'VID7' => "Welcome Meeting PART 2",
        //REVISOR Page
        'QUESTIONREV' => "Question",
        'ACTION' => "Action",
        'REVLINK' => "Start Revision",
        'REVSTUDY' => "Start Study",
        'STUDY' => "Under Study",
        'REVISION' => "Revision",
        'DATEWRITTEN' => "Date Written",
        'LO' => "Content suitabilitiy to Learning Outcome ",
        'REVCAUSE' => "Insert  Your Cause",
        'PALGRISM' => "Paligrism Checker",
        'PALGRISMTALK' => 'use the link (<a href="https://www.quetext.com/" target="_blank">https://www.quetext.com/</a>) or (<a href="https://www.duplichecker.com/" target="_blank">https://www.duplichecker.com/</a>) to log in the plagiarism checker and give us information about the plagiarism of the stem of item',
        // 'DOK' => "Depth of knowledge",same as depth
        'DOKEXTRA' => "The item is written at either DoK Level 2 (Basic Application) or DoK Level 3 (Strategic Thinking) Not in Dok Level 1 (Recall)",
        'DOKPROFF' => "Cause of DOK",// instead of DOK
        'DOKPROFFEXTRA' => "Why you choose this DOK",
        'ERROR' => "The item is free of content errors.",
        'KEY' => "The key is identified.",
        'KEYEXTRA' => "The correct choice is selected.",
        'IDENTIFIER' => "The identified key is correct",
        'IDENTIFIERONLY' => "The identified key is the ONLY correct option",
        'DISTRACTORS' => "All distractors are plausible",
        'DISTEXTRA' => "All distractors are positive and do not have a case of denial, cases as (Except)",
        'EXPLAIN' => "Explain Answer",
        'LANGEXTRA' => "Language, examples, and context are sensitive and free of bias.",
        'NEWQ' => "Question is new",
        'NEWQEXTRA' => "The item is independent of other items on the books. (Item avoids 'double jeopardy'.)",
        'GRAMMER' => "Grammer",
        'GRAMMEREXTRA' => "Grammar and spelling are correct.",
        'ABBREV' => "Abbreviation",
        'ABBREVEXTRA' => "Any Unknown abbreviation is defined within the item or test.",
        'SYMBOL' => "Symbols",
        'SYMBOLEXTRA' => "All symbols used in the item are familiar to test-takers.",
        'NEGATIVE' => "Negative words",
        'NEGATIVEEXTRA' => "Negative words such as EXCEPT or NOT are avoided unless absolutely necessary,and are written in capital letters",
        'LETTERS' => "A,B,C and D letters",
        'LETTERSEXTRA' => "If letters A, B, C, and D are used in the stimulus or stem, those specific letters are absolutely necessary.",
        'DRAWING' => "Supported Drawing",
        'DRAWINGEXTRA' => "All stimulus materials are clearly labeled.",
        'NEED' => "Needed Drawing",
        'NEEDEXTRA' => "All stimulus materials are needed to find the correct response.",
        'REC' => "Recommended modifications",
        'RECEXTRA' => "Recommended modifications to the stimulus",
        'STEMREV' => "End of Question",
        'STEMREVEXTRA' => "The stem is either open(.) or closed(?)",
        'SIMPLE' => "Simplicity of the Question",
        'SIMPLEEXTRA' => "The stem is easy to understand and direct",
        'THIRD' => "Side talking",
        'THIRDEXTRA' => "The stem is written as personal talking to examinant person.",
        'STEMMOD' => "Good Stem",
        'STEMMODEXTRA' => "Recommended modifications to the stem",
        'RESPOND' => "Answers",
        'RESPONDEXTRA' => "All response options (Answers) are related to the question/task in the stem.",
        'RESPEAS' => "Understandable options",
        'RESPEASEXTRA' => "All response options are easy to understand.",
        'RESTRICT' => "Unwanted option",
        'RESTRICTEXTRA' => "“All of the above,” “none of the above,” or similar phrases are NOT used in the response options.",
        'OPLENGTH' => "Option Length",
        'OPLENGTHEXTRA' => "All response options are of similar length, or in two sets of similar length.",
        'OPGRA' => "Options Grammer",
        'OPGRAEXTRA' => "All response options are grammatically  and spelling Correct.",
        'OPREAP' => "Options using words from question",
        'OPREAPEXTRA' => "All response options avoid using a repeated multiple-word phrase.",
        'WORDREAPEAT' => "Words are used",
        'WORDREAPEATEXTRA' => "If used, content words from the stem appear in two or four response options OR If used, words like “ALWAYS,” “NEVER” or “ALL” appear in two or four options.",
        'NOUN' => "Options Noun",
        'NOUNEXTRA' => "If used, proper nouns (as scientist name) appear in two or four options.",
        'OPNUM' => "Options using Numbers",
        'OPNUMEXTRA' => "If used, numerical response options are in ascending or descending order.",
        'OPDEC' => "Options Decimal Numbers",
        'OPDECEXTRA' => "If used, all numerical response options are similarly formatted, e.g., estimated to the same number of decimal places.",
        'OPMOD' => "Options are good",
        'OPMODEXTRA' => "Recommended modifications to the response options",
        'ACCEPT' => "Accept Question",
        'REPORT' => "Return a Report",
        'CANCEL' => "Cancel",
        // REVISOR PREPARE REPORT PAGE
        'REPORTPREPARE' => "Prepare Report",
        // CREATOR Re Revision
        'REVISORNAME' => "The Revisor Name",
        'RETURNED' => "Questions Returned from Revisor",
        'REVICE' => "Adjust Question",
        'REREVISE' => "Final Adjustment for Question",
        'PALIGRISMCHECKER' => "Palgiarism Checker",
        'PALIGRISM' => "Percentage of Matching the question to others on web",
        'STEMREPORT' => "Stem Notes",
        'RETURNTOREVISOR' => "Return to revisor",
        'REFSTATE' => "Reference Status",
        'REFSTATEEXTRA' => "The reference which is used in preparing the question",
    );
    return $lang[$phrase];
}
